### ISSUE TITLE
How might one connect a packet forwarder to non-DIY hotpsots?

### ISSUE THREAD

**Issue by trevorprater** [Carniverous19/helium-DIY-middleman#1]

**Comment by Carniverous19** [comment]
Unfortunately you cant (well fortunate for security), pretty much all official gateways are more locked down than DIY and dont have the ability to split the packet forwarder from the miner in order to route it through the middleman.

The ease of running this middleman code with DIY is one of the main issues with DIY's and why they are not allowed on-chain or to participate in PoC while the more locked down gateways are much less susceptible to data manipulation.

One of my main reasons for releasing this code publicly was to stop DIY's going on chain because it would just cause massive gaming with tools like this.

**Comment by bitbotz1466** [comment]
@Carniverous19 Carniverous19 when running command, python3 gateways2miners.py -p 1680 -c ./gateways 

![image](https://user-images.githubusercontent.com/91962519/136034706-f347c17d-60bd-4743-b34e-cb2a6c906ecd.png)
having issues testing software. would you be able to spot my problem? thank you!

**Comment by freakyherc01** [comment]
@Carniverous19 i run your code, but my 2 miners are receiving the same RSSI but different SNR all the time, you know what the issue?!
